name: build-components

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v2
              with:
                  node-version: "12"
            - name: Build Component Library
              run: |
                  yarn install
                  yarn build
